src/Entity/EntityTrait.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

trait EntityTrait
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function setTimeStamp(): void
    {
        if ($this->getCreatedAt() === null)
            $this->setCreatedAt(new \DateTimeImmutable());

        $this->setUpdatedAt(new \DateTime());
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use App\Entity\EntityTrait;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TaskRepository;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Task
{
    use EntityTrait;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\ManyToOne(targetEntity: TaskList::class, inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private $list;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getList(): ?TaskList
    {
        return $this->list;
    }

    public function setList(?TaskList $list): self
    {
        $this->list = $list;

        return $this;
    }
}

src/Entity/TaskList.php
<?php

namespace App\Entity;

use App\Entity\EntityTrait;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TaskListRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: TaskListRepository::class)]
#[ORM\HasLifecycleCallbacks]
class TaskList
{

    use EntityTrait;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\OneToMany(mappedBy: 'list', targetEntity: Task::class)]
    private $tasks;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'list')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setList($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getList() === $this) {
                $task->setList(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\TaskList;
use App\Repository\TaskListRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title',  TextType::class, [
                'label' => false,
                'constraints' => [
                    new NotBlank(['message' => 'Veuillez remplir le champs'])
                ],
                'attr' => [
                    'class' => 'form-control mb-3',
                    'style' => 'height:30px;',
                    'placeholder' => 'Entrer un titre'
                ]
            ])
            ->add('list', EntityType::class, [
                'class' => TaskList::class,
                'label' => false,
                'attr' => [
                    'class' => 'form-control mb-3',
                    'style' => 'color:grey'
                ],
                'placeholder' => 'Choisir une liste',
                'choice_label' => fn (TaskList $taskList) => $taskList->getName(),
                'constraints' => new NotBlank(['message' => 'Veuillez choisir une liste']),
                'query_builder' => function (TaskListRepository $taskListRepository) {
                    return $taskListRepository->createQueryBuilder('t')->orderBy('t.name', 'ASC');
                }
            ])
            ->add('submit', SubmitType::class, [
                'label' => "Valider",
                'attr' => [
                    'class' => 'btn btn-secondary mt-5',
                    'formnovalidate' => 'formnovalidate'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

declare(strict_types=1);

namespace App\Controller;


use App\Entity\Task;
use App\Form\TaskType;
use App\Entity\TaskList;
use App\Repository\TaskRepository;
use App\Repository\TaskListRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TaskController extends AbstractController
{
    private FlashyNotifier $flash;
    private EntityManagerInterface $em;
    public function __construct(FlashyNotifier $flash, EntityManagerInterface $em)
    {
        $this->flash = $flash;
        $this->em = $em;
    }

    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->redirectToRoute('read-index-lists');
    }

    #[Route('/task/lists', name: 'read-index-lists')]
    public function indexTasks(Request $request, TaskListRepository $taskListRepository): Response
    {
        return $this->render(
            'task/index.html.twig',
            ['taskLists' => $taskListRepository->findBy(['user' => $this->getUser()], ['name' => 'ASC'])]
        );
    }

    #[Route('/task/liste/{id}', name: 'read-list')]
    public function displayTaskList(TaskList $tasklist, TaskRepository $taskRepository): Response
    {
        return $this->render(
            'task/display_Tasks.html.twig',
            ['tasks' => $taskRepository->findBy(['list' => $tasklist->getId()]), 'tasklist' => $tasklist]
        );
    }

    #[Route('/task/new', name: 'create-task')]
    public function createNewTask(Request $request,): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $list = $form->get('list')->getData();
            $task->setList($list);
            $this->em->persist($task);
            $this->em->flush();

            $this->flash->success('Nouvelle tâche crée dans la liste ' . $list->getName(), '');
            return $this->redirectToRoute('read-list', ['id' => $list->getId()]);
        }
        return $this->render('task/task_form_page.html.twig', ['form' => $form->createView()]);
    }

    #[Route('/task/update', name: 'update-task')]
    public function updateTask(Request $request, TaskRepository $taskRepository): Response
    {
        if (!$request->isXmlHttpRequest())
            return new Response('La requete à renvoyé un problème', 400);

        $data = json_decode($request->getContent(), true);

        $task  = $taskRepository->findOneBy(['id' => $data['id']]);
        $task->setTitle($data['title']);
        $this->em->flush();

        return new JsonResponse(json_encode(array('msg' => 'task updated successfully')), 200);
    }

    #[Route('/task/delete/{id}', name: 'delete-task')]
    public function delete_task(Task $task, Request $request): Response
    {
        $this->em->remove($task);
        $this->em->flush();
        $this->flash->success('Tache supprimée avec succès', '');

        return $this->redirect($request->headers->get('referer'));
    }
}

templates/task/display_tasks.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}Mes listes
{% endblock %}

{% block body %}
	<div class="container p-5">
		<div class="row mt-5">

			<div class="d-flex justify-content-between">
				<H5>{{ tasklist.name ~ ' (' ~  pluriel( tasklist.tasks | length , 'task)', 'tasks)') }}</H5>
				<a href="{{ path('create-task') }}">
					<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewbox="0 0 50 50" style=" fill:#000000;">
						<path d="M25,2C12.317,2,2,12.317,2,25s10.317,23,23,23s23-10.317,23-23S37.683,2,25,2z M37,26H26v11h-2V26H13v-2h11V13h2v11h11V26z"></path>
					</svg>
				</a>
			</div>
			<small>
				<a href="{{ path('read-index-lists') }}">back</a>
			</small>

			{% if tasklist.tasks | length == 0 %}
				<h5 class="mt-5">Aucune tache en cours</h5>
			{% else %}
				<table class="table table-striped mt-5" style="width:100%;overflow:scroll">
					<thead>
						<tr>
							<th scope="col">Titre</th>
							<th scope="col">Date création</th>
							<th scope="col">Dernière MAJ</th>
							<th scope="col">Supprimer</th>
						</tr>
					</thead>
					<tbody>
						{% for task in tasks %}
							<tr>
								<td class="d-flex">
									<span class='d-block'>{{ task.title }}</span>
									&nbsp;
									<a type="button" class="update">
										<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="25" viewbox="0 0 32 32" style=" fill:#000000;">
											<path d="M 23.90625 3.96875 C 22.859375 3.96875 21.8125 4.375 21 5.1875 L 5.1875 21 L 5.125 21.3125 L 4.03125 26.8125 L 3.71875 28.28125 L 5.1875 27.96875 L 10.6875 26.875 L 11 26.8125 L 26.8125 11 C 28.4375 9.375 28.4375 6.8125 26.8125 5.1875 C 26 4.375 24.953125 3.96875 23.90625 3.96875 Z M 23.90625 5.875 C 24.410156 5.875 24.917969 6.105469 25.40625 6.59375 C 26.378906 7.566406 26.378906 8.621094 25.40625 9.59375 L 24.6875 10.28125 L 21.71875 7.3125 L 22.40625 6.59375 C 22.894531 6.105469 23.402344 5.875 23.90625 5.875 Z M 20.3125 8.71875 L 23.28125 11.6875 L 11.1875 23.78125 C 10.53125 22.5 9.5 21.46875 8.21875 20.8125 Z M 6.9375 22.4375 C 8.136719 22.921875 9.078125 23.863281 9.5625 25.0625 L 6.28125 25.71875 Z"></path>
										</svg>
									</a>
									<a type="button" class="updateTask d-none" data-idtask="{{ task.id }}">
										<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewbox="0 0 24 24" class="mt-1" style=" fill:#000000;">
											<path d="M 12 0 C 5.371094 0 0 5.371094 0 12 C 0 18.628906 5.371094 24 12 24 C 18.628906 24 24 18.628906 24 12 C 24 5.371094 18.628906 0 12 0 Z M 11 17.414063 L 6.292969 12.707031 L 7.707031 11.292969 L 11 14.585938 L 18.292969 7.292969 L 19.707031 8.707031 Z"></path>
										</svg>
									</a>
								</td>
								<td>{{ task.createdAt | date('d/m/Y')}}</td>
								<td>{{ task.updatedAt | date('d/m/Y')}}</td>
								<td>
									<small>
										<a href="#" class="button" data-id="{{ task.id }}">
											<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="25" viewbox="0 0 24 24" style=" fill:#000000;">
												<path d="M 10 2 L 9 3 L 5 3 C 4.4 3 4 3.4 4 4 C 4 4.6 4.4 5 5 5 L 7 5 L 17 5 L 19 5 C 19.6 5 20 4.6 20 4 C 20 3.4 19.6 3 19 3 L 15 3 L 14 2 L 10 2 z M 5 7 L 5 20 C 5 21.1 5.9 22 7 22 L 17 22 C 18.1 22 19 21.1 19 20 L 19 7 L 5 7 z M 9 9 C 9.6 9 10 9.4 10 10 L 10 19 C 10 19.6 9.6 20 9 20 C 8.4 20 8 19.6 8 19 L 8 10 C 8 9.4 8.4 9 9 9 z M 15 9 C 15.6 9 16 9.4 16 10 L 16 19 C 16 19.6 15.6 20 15 20 C 14.4 20 14 19.6 14 19 L 14 10 C 14 9.4 14.4 9 15 9 z">></svg>
											</a>
										</small>
									</td>
								</td>
							</tr>
							{{ include('partials/delete_task_confirmation.html.twig') }}
						{% endfor %}
					</tbody>
				</table>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/task/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}Mes listes
{% endblock %}

{% block body %}
	<div class="container p-5">
		<div class="row mt-5">

			<H5>Mes listes</H5>
			{% for taskList in taskLists %}
				<div class="col-sm-6" style="width:18em">
					<div class="card shadow">
						<div class="card-body">
							<h5 class="card-title">{{ taskList.name }}</h5>
							<small class="card-text mb-2 d-block">{{ 'Crée le ' ~ taskList.createdAt | date('d/m/Y') }}</small>
							<a href="{{ path('read-list', { id: taskList.id }) }}" class="btn btn-secondary">voir la liste</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>

	</div>
{% endblock %}

templates/task/task_form_page.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}Mes listes
{% endblock %}

{% block body %}
	<div class="row mt-5">
		<div class="col-md-5 mx-auto">
			<div class="bg-dark p-5 rounded mt-5">
				{{ form_start(form)}}

				<h5 class="text-white text-center mb-5">
					{{ app.request.attributes.get('_route') == 'create-task' ? 'Ajouter une tâche' : 'Modifier une tâche' }}
				</h5>
				<div class="mb-3">
					{{ form_row(form.title)}}
					<small class='text-danger form-error'>{{ form_errors(form.title)}}</small>
				</div>
				<div class="mb-3">
					{{ form_row(form.list)}}
					<small class='text-danger form-error'>{{ form_errors(form.list)}}</small>
				</div>
				<div class="d-flex">
					<div class="mb-3">
						{{ form_row(form.submit)}}
					</div>
					&nbsp;&nbsp;
					<div class="mb-3">
						<a href="{{ path('read-index-lists') }}" class="btn btn-danger mt-5">Annuler</a>
					</div>
				</div>

				{{ form_end(form)}}
			</div>
		</div>
	</div>
{% endblock %}